[CI/CD] Enhance nightly benchmark CI workflow to support xpu and hpu clusters
Added support for xpu and hpu cluster types in CI workflow.

Signed-off-by: maugustosilva <marcio.a.silva@ibm.com>

diff --git a/.github/workflows/reusable-ci-nightly-benchmark.yaml b/.github/workflows/reusable-ci-nightly-benchmark.yaml
--- a/.github/workflows/reusable-ci-nightly-benchmark.yaml
+++ b/.github/workflows/reusable-ci-nightly-benchmark.yaml
@@ -172,6 +172,14 @@ jobs:
           if [[ ! -z $IS_ROCM ]]; then
             export CLUSTER_TYPE=rocm
           fi
+          IS_XPU=$(echo "${{ github.workflow }}" | grep -i "\xpu" || true)$(echo "${{ inputs.standup_scenario }}" | grep -i "xpu" || true)
+          if [[ ! -z $IS_XPU ]]; then
+            export CLUSTER_TYPE=xpu
+          fi
+          IS_HPU=$(echo "${{ github.workflow }}" | grep -i "\hpu" || true)$(echo "${{ inputs.standup_scenario }}" | grep -i "hpu" || true)
+          if [[ ! -z $IS_HPU ]]; then
+            export CLUSTER_TYPE=hpu
+          fi
           echo "Cluster provider is \"$CLUSTER_TYPE\""
           echo "cluster_type=$CLUSTER_TYPE" >> "$GITHUB_OUTPUT"
           echo "CLUSTER_TYPE=$CLUSTER_TYPE" >> "$GITHUB_ENV"
@@ -186,6 +194,12 @@ jobs:
           elif [[ "$CLUSTER_TYPE" == "rocm" ]]; then
             echo "Targetting self-hosted runners (AMD/CI)"
             RUNNERS_JSON_LIST='["rocm"]'
+          elif [[ "$CLUSTER_TYPE" == "xpu" ]]; then
+            echo "Targetting self-hosted runners (Intel/CI)"
+            RUNNERS_JSON_LIST='["xpu"]'
+          elif [[ "$CLUSTER_TYPE" == "hpu" ]]; then
+            echo "Targetting self-hosted runners (Intel/CI)"
+            RUNNERS_JSON_LIST='["hpu-dispatch-runner"]'
           else
             echo "Targetting hosted runners (non-OpenShift)"
             RUNNERS_JSON_LIST='["ubuntu-latest"]'
@@ -216,7 +230,7 @@ jobs:
       LLMDBENCH_WORKSPACE: ${{ inputs.workspace_dir || '/tmp/llmdbenchcicd' }}
       LLMDBENCH_HF_TOKEN: ${{ secrets.LLMDBENCH_HF_TOKEN }}
       HF_TOKEN: ${{ secrets.LLMDBENCH_HF_TOKEN }}
-      LLMDBENCH_GATEWAY_CLASS: ${{ inputs.gateway_class || 'istio' }}
+      LLMDBENCH_CICD_GATEWAY_CLASS: ${{ inputs.gateway_class || 'istio' }}
       LLMDBENCH_IS_DRY_RUN: ${{ inputs.dry_run || 'false' }}
       LLMDBENCH_IS_VERBOSE: ${{ inputs.verbose || 'false' }}
       LLMDBENCH_MONITORING_ENABLED: ${{ inputs.monitoring_enabled || 'true' }}
@@ -275,12 +289,13 @@ jobs:
           if [[ $LLMDBENCH_CICD_TARGET == "cks" ]]; then
             echo "Selected \"Coreweave\" kubeconfig"
             echo "${{ secrets.KUBECONFIG_DATA_CKS }}" | base64 -d > ~/.kube/config
+            chmod 600 ~/.kube/config
           fi
           if [[ $LLMDBENCH_CICD_TARGET == "ocp" ]]; then
             echo "Selected \"OpenShift\" kubeconfig"
             echo "${{ secrets.KUBECONFIG_DATA_OCP }}" | base64 -d > ~/.kube/config
+            chmod 600 ~/.kube/config
           fi
-          chmod 600 ~/.kube/config
         shell: bash
 
       - name: Install oc (optional on install.sh)
@@ -301,15 +316,33 @@ jobs:
             fi
           fi
 
+      - name: Install specific yq version
+        uses: frenck/action-setup-yq@v1
+        with:
+          version: 'v4.53.2'
+
       - name: Show cluster names
         run: |
-          echo "### Cluster names: $(cat ~/.kube/config | yq ".clusters[].name" | sed ':a;N;$!ba;s/\n/, /g')"
-          exit $?
+          echo "### Attempting to list cluster names..."
+          if [[ -f ~/.kube/config ]]; then
+            echo "### Cluster names (from \"~/.kube/config\") : $(cat ~/.kube/config | yq ".clusters[].name" | sed ':a;N;$!ba;s/\n/, /g')"
+          fi
+          if [[ ! -z $KUBECONFIG ]]; then
+            echo "### Cluster names (from \"$KUBECONFIG\") : $(cat $KUBECONFIG | yq ".clusters[].name" | sed ':a;N;$!ba;s/\n/, /g')"
+          fi
         shell: bash
 
       - name: Show cluster nodes
         run: |
+          echo "### Attempting to list node names..."
           kubectl get node
+          exit $?
+        shell: bash
+
+      - name: Show cluster storageclasses
+        run: |
+          echo "### Attempting to list storage classes..."
+          kubectl get storageclass
           exit $?
         shell: bash
 
@@ -374,29 +407,6 @@ jobs:
           echo "### llm-d-benchmark code is present (branch $(git branch --show-current))"
         shell: bash
 
-      - name: Set up extra command line parameters
-        run: |
-          export LLMDBENCH_EXTRA_CMD=""
-          export LLMDBENCH_EXTRA_OPERATION_CMD=""
-
-          if [[ "$LLMDBENCH_IS_DRY_RUN" == "true" ]]; then
-            export LLMDBENCH_EXTRA_CMD="--dry-run"
-          fi
-          if [[ "$LLMDBENCH_IS_VERBOSE" == "true" ]]; then
-            export LLMDBENCH_EXTRA_CMD="--verbose $LLMDBENCH_EXTRA_CMD "
-          fi
-          if [[ "$LLMDBENCH_MONITORING_ENABLED" == "false" ]]; then
-            export LLMDBENCH_EXTRA_OPERATION_CMD="--no-monitoring $LLMDBENCH_EXTRA_OPERATION_CMD "
-          fi
-          echo "### LLMDBENCH_EXTRA_CMD is \"$LLMDBENCH_EXTRA_CMD\""
-          echo "LLMDBENCH_EXTRA_CMD=$LLMDBENCH_EXTRA_CMD" >> $GITHUB_ENV
-          echo "### LLMDBENCH_EXTRA_OPERATION_CMD is \"$LLMDBENCH_EXTRA_OPERATION_CMD\""
-          echo "LLMDBENCH_EXTRA_OPERATION_CMD=$LLMDBENCH_EXTRA_OPERATION_CMD" >> $GITHUB_ENV
-          export LLMDBENCH_GATEWAY_CLASS=$(echo "$LLMDBENCH_GATEWAY_CLASS" | sed 's^standalone^epponly^g')
-          echo "LLMDBENCH_GATEWAY_CLASS is \"$LLMDBENCH_GATEWAY_CLASS\""
-          echo "LLMDBENCH_GATEWAY_CLASS=$LLMDBENCH_GATEWAY_CLASS"  >> $GITHUB_ENV
-        shell: bash
-
       - name: Conditionally clone llm-d from main repo
         run: |
           #find ~ -type f -name "cks_nvshmem3.3.9.patch" -print
@@ -414,6 +424,7 @@ jobs:
 
       - name: Apply overrides to scenarios
         run: |
+          touch ~/work/lkcmd.txt
           if [[ $LLMDBENCH_CICD_METHOD == "kustomize" ]]; then
             echo "### Overriding \"repoPath\" to \"$HOME/work/llm-d/llm-d\""
             yq -i ".scenario[0].kustomize.repoPath = \"$HOME/work/llm-d/llm-d\"" ~/work/llm-d-benchmark/llm-d-benchmark/config/scenarios/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO.yaml
@@ -430,31 +441,47 @@ jobs:
               yq -i '.scenario[0].storage.workloadPvc.storageClassName = "ibm-spectrum-scale-fileset"' ~/work/llm-d-benchmark/llm-d-benchmark/config/scenarios/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO.yaml
             fi
             echo "### Setting \"INFRA_PROVIDER\" to \"$LLMDBENCH_CICD_INFRA_PROVIDER\""
-            yq -i ".scenario[0].kustomize.guideVariableOverrides.INFRA_PROVIDER = \"$LLMDBENCH_CICD_INFRA_PROVIDER\"" ~/work/llm-d-benchmark/llm-d-benchmark/config/scenarios/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO.yaml
+            lkcmd="yq -i \".scenario[0].kustomize.guideVariableOverrides.INFRA_PROVIDER = \\\"$LLMDBENCH_CICD_INFRA_PROVIDER\\\"\" ~/work/llm-d-benchmark/llm-d-benchmark/config/scenarios/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO.yaml"
+            echo -n "$lkcmd" > ~/work/lkcmd.txt
+            eval $lkcmd
             cat ~/work/llm-d-benchmark/llm-d-benchmark/config/scenarios/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO.yaml | yq '.scenario[0].kustomize.guideVariableOverrides.INFRA_PROVIDER'
-            export LLMDBENCH_CICD_BACKEND_ACCELERATOR=$(echo $LLMDBENCH_CICD_ACCELERATOR/$LLMDBENCH_CICD_BACKEND/$LLMDBENCH_CICD_CONNECTOR/ | sed 's^//^/^g')
+            if [[ ! -z $LLMDBENCH_CICD_CONNECTOR ]]; then
+            echo "### Setting \"CONNECTOR\" to \"$LLMDBENCH_CICD_CONNECTOR\""
+              lkcmd="yq -i \".scenario[0].kustomize.guideVariableOverrides.CONNECTOR = \\\"$LLMDBENCH_CICD_CONNECTOR\\\"\" ~/work/llm-d-benchmark/llm-d-benchmark/config/scenarios/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO.yaml"
+              echo -n "; $lkcmd" >> ~/work/lkcmd.txt
+              eval $lkcmd
+              cat ~/work/llm-d-benchmark/llm-d-benchmark/config/scenarios/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO.yaml | yq '.scenario[0].kustomize.guideVariableOverrides.CONNECTOR'
+            fi
+            export LLMDBENCH_CICD_BACKEND_ACCELERATOR=$(echo $LLMDBENCH_CICD_ACCELERATOR/$LLMDBENCH_CICD_BACKEND | sed 's^//^/^g')
             echo "### Setting \"acceleratorBackend\" to \"$LLMDBENCH_CICD_BACKEND_ACCELERATOR\""
-            yq -i ".scenario[0].kustomize.acceleratorBackend = \"$LLMDBENCH_CICD_BACKEND_ACCELERATOR\"" ~/work/llm-d-benchmark/llm-d-benchmark/config/scenarios/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO.yaml
+            lkcmd="yq -i \".scenario[0].kustomize.acceleratorBackend = \\\"$LLMDBENCH_CICD_BACKEND_ACCELERATOR\\\"\" ~/work/llm-d-benchmark/llm-d-benchmark/config/scenarios/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO.yaml"
+            echo -n "; $lkcmd" >> ~/work/lkcmd.txt
+            eval $lkcmd
             cat ~/work/llm-d-benchmark/llm-d-benchmark/config/scenarios/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO.yaml | yq '.scenario[0].kustomize.acceleratorBackend'
+            LLMDBENCH_CICD_KUSTOMIZE_PATH=~/work/llm-d/llm-d/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO/$LLMDBENCH_CICD_CONNECTOR/modelserver/$LLMDBENCH_CICD_ACCELERATOR/$LLMDBENCH_CICD_BACKEND
+            echo "Kustomize full path is \"$LLMDBENCH_CICD_KUSTOMIZE_PATH\""
+            detected_model=$(kubectl kustomize $LLMDBENCH_CICD_KUSTOMIZE_PATH  yq .spec.template.spec.containers[0].args | grep -Ev "\- \--|\- '|\---|null" | uniq | cut -d ' ' -f 2)
+            echo "LLMDBENCH_CICD_DETECTED_MODEL is \"$detected_model\""
+            echo "LLMDBENCH_CICD_DETECTED_MODEL=$detected_model"  >> $GITHUB_ENV
             echo " ### Setting priority class \"$LLMDBENCH_CICD_PRIORITY_CLASS\" on scenario \"$LLMDBENCH_CICD_SCENARIO\""
             for i in vllm decode prefill; do
-              find ~/work/llm-d/llm-d/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO/modelserver/ -type f -name "patch-$i.yaml" -exec yq ".spec.template.spec.priorityClassName=\"nightly-gpu-critical\"" -i {} \;
-              find ~/work/llm-d/llm-d/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO/modelserver/ -type f -name "patch-$i.yaml" -print -exec yq '.spec.template.spec.priorityClassName' {} \;
+              find $LLMDBENCH_CICD_KUSTOMIZE_PATH -type f -name "patch-$i.yaml" -exec yq ".spec.template.spec.priorityClassName=\"$LLMDBENCH_CICD_PRIORITY_CLASS\"" -i {} \;
+              find $LLMDBENCH_CICD_KUSTOMIZE_PATH -type f -name "patch-$i.yaml" -print -exec yq '.spec.template.spec.priorityClassName' {} \;
             done
             export LLMDBENCH_CICD_DECODE_PODS="${{ inputs.decode_pods }}"
             if [[ $LLMDBENCH_CICD_DECODE_PODS != "auto" ]]; then
               echo "### Setting decode pods to \"$LLMDBENCH_CICD_DECODE_PODS\" on scenario \"$LLMDBENCH_CICD_SCENARIO\""
               for i in vllm decode; do
-                find ~/work/llm-d/llm-d/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO/modelserver/ -type f -name "patch-$i.yaml" -exec yq ".spec.replicas=$LLMDBENCH_CICD_DECODE_PODS" -i {} \;
-                find ~/work/llm-d/llm-d/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO/modelserver/ -type f -name "patch-$i.yaml" -print -exec yq ".spec.replicas" {} \;
+                find $LLMDBENCH_CICD_KUSTOMIZE_PATH -type f -name "patch-$i.yaml" -exec yq ".spec.replicas=$LLMDBENCH_CICD_DECODE_PODS" -i {} \;
+                find $LLMDBENCH_CICD_KUSTOMIZE_PATH -type f -name "patch-$i.yaml" -print -exec yq ".spec.replicas" {} \;
               done
             fi
             export LLMDBENCH_CICD_PREFILL_PODS="${{ inputs.prefill_pods }}"
             if [[ $LLMDBENCH_CICD_PREFILL_PODS != "auto" ]]; then
               echo "### Setting decode pods to \"$LLMDBENCH_CICD_PREFILL_PODS\" on scenario \"$LLMDBENCH_CICD_SCENARIO\""
               for i in prefill; do
-                find ~/work/llm-d/llm-d/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO/modelserver/ -type f -name "patch-$i.yaml" -exec yq ".spec.replicas=$LLMDBENCH_CICD_DECODE_PODS" -i {} \;
-                find ~/work/llm-d/llm-d/$LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO/modelserver/ -type f -name "patch-$i.yaml" -print -exec yq ".spec.replicas" {} \;
+                find $LLMDBENCH_CICD_KUSTOMIZE_PATH -type f -name "patch-$i.yaml" -exec yq ".spec.replicas=$LLMDBENCH_CICD_DECODE_PODS" -i {} \;
+                find $LLMDBENCH_CICD_KUSTOMIZE_PATH -type f -name "patch-$i.yaml" -print -exec yq ".spec.replicas" {} \;
               done
             fi
           fi
@@ -464,27 +491,59 @@ jobs:
           fi
         shell: bash
 
+      - name: Set up extra command line parameters
+        run: |
+          export LLMDBENCH_EXTRA_CMD=""
+          export LLMDBENCH_EXTRA_OPERATION_CMD=""
+          if [[ $LLMDBENCH_CICD_METHOD == "kustomize" ]]; then
+            export LLMDBENCH_EXTRA_CMD="--non-admin"
+          fi
+          if [[ "$LLMDBENCH_IS_DRY_RUN" == "true" ]]; then
+            export LLMDBENCH_EXTRA_CMD="--dry-run"
+          fi
+          if [[ "$LLMDBENCH_IS_VERBOSE" == "true" ]]; then
+            export LLMDBENCH_EXTRA_CMD="--verbose $LLMDBENCH_EXTRA_CMD "
+          fi
+          if [[ "$LLMDBENCH_MONITORING_ENABLED" == "false" ]]; then
+            export LLMDBENCH_EXTRA_OPERATION_CMD="--no-monitoring $LLMDBENCH_EXTRA_OPERATION_CMD "
+          fi
+          if [[ ! -z $LLMDBENCH_CICD_DETECTED_MODEL ]]; then
+            export LLMDBENCH_EXTRA_OPERATION_CMD="--model $LLMDBENCH_CICD_DETECTED_MODEL $LLMDBENCH_EXTRA_OPERATION_CMD "
+          fi
+          echo "### LLMDBENCH_EXTRA_CMD is \"$LLMDBENCH_EXTRA_CMD\""
+          echo "LLMDBENCH_EXTRA_CMD=$LLMDBENCH_EXTRA_CMD" >> $GITHUB_ENV
+          echo "### LLMDBENCH_EXTRA_OPERATION_CMD is \"$LLMDBENCH_EXTRA_OPERATION_CMD\""
+          echo "LLMDBENCH_EXTRA_OPERATION_CMD=$LLMDBENCH_EXTRA_OPERATION_CMD" >> $GITHUB_ENV
+          export LLMDBENCH_CICD_GATEWAY_CLASS=$(echo "$LLMDBENCH_CICD_GATEWAY_CLASS" | sed 's^standalone^epponly^g')
+          echo "LLMDBENCH_CICD_GATEWAY_CLASS is \"$LLMDBENCH_CICD_GATEWAY_CLASS\""
+          echo "LLMDBENCH_CICD_GATEWAY_CLASS=$LLMDBENCH_CICD_GATEWAY_CLASS"  >> $GITHUB_ENV
+        shell: bash
+
       - name: Cleanup target cloud
         run: |
           cd ~/work/llm-d-benchmark/llm-d-benchmark/
-          LLMDBENCH_CMD="llmdbenchmark --spec $LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO $LLMDBENCH_EXTRA_CMD teardown --namespace $LLMDBENCH_CICD_NS --release $LLMDBENCH_CICD_R --gateway-class $LLMDBENCH_GATEWAY_CLASS --methods $LLMDBENCH_CICD_METHOD"
-          echo "### $LLMDBENCH_CMD ###"
-          $LLMDBENCH_CMD
+          LLMDBENCH_CMD="llmdbenchmark --spec $LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO $LLMDBENCH_EXTRA_CMD teardown --namespace $LLMDBENCH_CICD_NS --release $LLMDBENCH_CICD_R --gateway-class $LLMDBENCH_CICD_GATEWAY_CLASS --methods $LLMDBENCH_CICD_METHOD"
+          echo "### $(cat ~/work/lkcmd.txt); $LLMDBENCH_CMD ###"
+          eval $LLMDBENCH_CMD
           kubectl -n "$LLMDBENCH_CICD_NS" exec -i access-to-harness-data-workload-pvc -- bash -c "rm -rf /requests/*" || true
         shell: bash
 
       - name: Standup
         run: |
           cd ~/work/llm-d-benchmark/llm-d-benchmark/
-          LLMDBENCH_CMD="llmdbenchmark --spec $LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO $LLMDBENCH_EXTRA_CMD standup $LLMDBENCH_EXTRA_OPERATION_CMD --namespace $LLMDBENCH_CICD_NS --gateway-class $LLMDBENCH_GATEWAY_CLASS --release $LLMDBENCH_CICD_R --methods $LLMDBENCH_CICD_METHOD"
-          echo "### $LLMDBENCH_CMD ###"
-          $LLMDBENCH_CMD
+          LLMDBENCH_CMD="llmdbenchmark --spec $LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO $LLMDBENCH_EXTRA_CMD standup $LLMDBENCH_EXTRA_OPERATION_CMD --namespace $LLMDBENCH_CICD_NS --gateway-class $LLMDBENCH_CICD_GATEWAY_CLASS --release $LLMDBENCH_CICD_R --methods $LLMDBENCH_CICD_METHOD"
+          echo "### $(cat ~/work/lkcmd.txt); $LLMDBENCH_CMD ###"
+          eval $LLMDBENCH_CMD
         shell: bash
 
       - name: Debug info (on failure)
         if: failure()
         run: |
-          /usr/local/bin/debug_info_on_failure.sh "$LLMDBENCH_CICD_NS"
+          if [[ -f /usr/local/bin/debug_info_on_failure.sh ]]; then
+            /usr/local/bin/debug_info_on_failure.sh "$LLMDBENCH_CICD_NS"
+          else
+            echo "### Unable to obtain debug info"
+          fi
         shell: bash
 
       - name: Run
@@ -498,8 +557,8 @@ jobs:
             echo "Temporarily unable to test \"fma\" on \"cks\" clusters"
           else
             LLMDBENCH_CMD="llmdbenchmark --spec $LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO $LLMDBENCH_EXTRA_CMD run --namespace $LLMDBENCH_CICD_NS --methods $LLMDBENCH_CICD_METHOD --harness $LLMDBENCH_CICD_HARNESS --workload $LLMDBENCH_CICD_WORKLOAD --data-access-timeout 1200"
-            echo "### $LLMDBENCH_CMD ###"
-            $LLMDBENCH_CMD
+            echo "### $(cat ~/work/lkcmd.txt); $LLMDBENCH_CMD ###"
+            eval $LLMDBENCH_CMD
           fi
         shell: bash
 
@@ -507,7 +566,7 @@ jobs:
         if: always()
         run: |
           cd ~/work/llm-d-benchmark/llm-d-benchmark/
-          LLMDBENCH_CMD="llmdbenchmark --spec $LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO $LLMDBENCH_EXTRA_CMD teardown --namespace $LLMDBENCH_CICD_NS --gateway-class $LLMDBENCH_GATEWAY_CLASS --release $LLMDBENCH_CICD_R --methods $LLMDBENCH_CICD_METHOD"
+          LLMDBENCH_CMD="llmdbenchmark --spec $LLMDBENCH_CICD_SCENARIO_DIR/$LLMDBENCH_CICD_SCENARIO $LLMDBENCH_EXTRA_CMD teardown --namespace $LLMDBENCH_CICD_NS --gateway-class $LLMDBENCH_CICD_GATEWAY_CLASS --release $LLMDBENCH_CICD_R --methods $LLMDBENCH_CICD_METHOD"
           echo "### $LLMDBENCH_CMD ###"
           $LLMDBENCH_CMD
           kubectl -n "$LLMDBENCH_CICD_NS" exec -i access-to-harness-data-workload-pvc -- bash -c "rm -rf /requests/*" || true
@@ -516,7 +575,11 @@ jobs:
       - name: Debug info (on failure)
         if: failure()
         run: |
-          /usr/local/bin/debug_info_on_failure.sh "$LLMDBENCH_CICD_NS"
+          if [[ -f /usr/local/bin/debug_info_on_failure.sh ]]; then
+            /usr/local/bin/debug_info_on_failure.sh "$LLMDBENCH_CICD_NS"
+          else
+            echo "### Unable to obtain debug info"
+          fi
         shell: bash
 
       - name: Upload results to GCS
